OMG ITS PYTHON TRY EXCEPT OMGOMGOMGOMGOGMOGMOMG

try - define a block of code to be tested for errors
throw - throws an exception when a problem is detected - let us create a custom error
catch - define a block of code to be executed, if an error occurs in the try block;

throw throws out an exception - catch catches what is thrown;

		try {
		// Block of code to try
		throw exception; // Throw an exception when a problem arise
		}
		catch () {
		// Block of code to handle errors
		}

Example:

		try {
		int age = 15;
		if (age >= 18) {
			cout << "Access granted - you are old enough.";
		} else {
			throw (age);
		}
		}
		catch (int myNum) {
		cout << "Access denied - You must be at least 18 years old.\n";
		cout << "Age is: " << myNum;
		}

To handle any exception, use ...

		try{
			throw ();
		}
		catch (...){
			cout << stuff;
		}


and of course
exception is a object

Example:

		using namespace std;

		int main() {
		try {
			// This code might throw an exception
			int x = 1 / 0;
		} catch (exception& e) {
			// This code will be executed if an exception is thrown
			cout << "Exception caught: " << e.what() << endl;
		}
		return 0;
		}